<div class="container space-2">
  <h1>Earn <span class="font-weight-semi-bold">Incentives</span></h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-primary breadcrumb-white">
      <li class="breadcrumb-item">
        <a class="breadcrumb-link" href="<?php echo $this->url('home'); ?>">Home</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Incentives</li>
    </ol>
  </nav>

  <div class="row">
    <div class="col-lg-8">
      <div id="learnSection" class="clearfix border-bottom">
        <div class="container">
          <!-- Title -->
          <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-9">
            <p>Signup and get your referal codes.</p>
          </div>
          <!-- End Title -->

          <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-12">
              <div class="float-right">
                <form id="myForm" method="post" action="<?php echo $this->url('incentive'); ?>">
                  <input type="hidden" name="id" value="test">
                  <button id="myButton" type="submit" class="btn btn-success">Get Referal Code</button>
                </form>
              </div>
              <div class="clearfix"></div><br>

              <?php
              echo $this->paginationControl(
                  $this->paginator,
                  'sliding',
                  "partial/home/paginator.phtml",
                  array(
                    'route' => 'projects',
                    'search_by' => $this->search_by,
                  )
              );
            ?>

              <?php foreach ($paginator as $row): ?>
                <article class="d-block card border-0 mb-7">
                  <div class="card-body p-0">
                    <div class="row">
                      <div class="col-sm-5 mb-5 mb-sm-0">
                        <a href="<?php echo $this->url('project', array('action' => 'view', 'id' => $row->getId(),)); ?>"><img class="img-fluid w-100 rounded" src="/img/project/<?php echo $row->getId(); ?>/photo-480x320.jpg" alt="<?php echo $this->escapehtml($row->getName()); ?>"></a>
                      </div>
                      <div class="col-sm-7">
                        <div class="pr-4">
                          <div>
                            <h2 class="h5">
                              <a href="<?php echo $this->url('project', array('action' => 'view', 'id' => $row->getId(),)); ?>"><?php echo $this->escapehtml($row->getName()); ?></a>
                            </h2>
                            <p><?php echo $this->escapehtml($row->getDescription()); ?></p>
                          </div>
                          <div class="form-group">
                            <textarea class="form-control copy_url"><?php echo $this->config['baseUrl']; ?>project/view/<?php echo $this->escapehtml($row->getId()); ?>?ref=<?php echo $this->referalId; ?></textarea>
                          </div>
                          <button class="btn btn-primary copy_button">Copy text</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>

              <?php endforeach; ?>

              <?php
              echo $this->paginationControl(
                  $this->paginator,
                  'sliding',
                  "partial/home/paginator.phtml",
                  array(
                    'route' => 'projects',
                    'search_by' => $this->search_by,
                  )
              );
            ?>

            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <h5 class="card-header">Refer and earn incentives!</h5>
        <div class="card-body">
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          <ul>
            <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</li>
            <li>when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centurie</li>
            <li>but also the leap into electronic typesetting, remaining essentially unchanged</li>
            <li> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages</li>
          </ul>
        </div>
      </div>
    </div>
  </div>


</div>
<script>
$(document).ready(function() {
 $(".copy_button").click(function() {
   prompt('Press Ctrl + C, then Enter to copy to clipboard', $(this).closest('div').find('.copy_url').val());
 });
 $("#myForm").submit(function() {
   return signin();
 });
})
</script>
