<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <?php echo $this->headTitle($this->translate('ProsperEOS'))->setSeparator(' - ')->setAutoEscape(false) ?>
      <?php echo $this->headMeta()
          ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
          ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ?>
      <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                      ->prependStylesheet($this->basePath() . '/css/style.css')
                      ->prependStylesheet($this->basePath() . '/assets/css/theme.css')
                      ->prependStylesheet($this->basePath() . '/assets/vendor/slick-carousel/slick/slick.css')
                      ->prependStylesheet($this->basePath() . '/assets/vendor/fancybox/jquery.fancybox.css')
                      ->prependStylesheet($this->basePath() . '/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css')
                      ->prependStylesheet($this->basePath() . '/assets/vendor/hs-megamenu/src/hs.megamenu.css')
                      ->prependStylesheet($this->basePath() . '/assets/vendor/animate.css/animate.min.css')
                      ->prependStylesheet($this->basePath() . '/assets/vendor/font-awesome/css/fontawesome-all.min.css')
                      ->prependStylesheet('//fonts.googleapis.com/css?family=Poppins:300,400,500,600,700') ?>
                      <?php echo $this->headScript()
                        //  JS Front
                        ->prependFile($this->basePath() . '/assets/js/components/hs.go-to.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.svg-injector.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.show-animation.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.slick-carousel.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.fancybox.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.validation.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.malihu-scrollbar.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.focus-state.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.unfold.js')
                        ->prependFile($this->basePath() . '/assets/js/components/hs.header.js')
                        ->prependFile($this->basePath() . '/assets/js/hs.core.js')

                        // JS Implementing Plugins
                        ->prependFile($this->basePath() . '/assets/vendor/slick-carousel/slick/slick.js')
                        ->prependFile($this->basePath() . '/assets/vendor/typed.js/lib/typed.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/fancybox/jquery.fancybox.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/jquery-validation/dist/jquery.validate.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/jquery-validation/dist/jquery.validate.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/svg-injector/dist/svg-injector.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/hs-megamenu/src/hs.megamenu.js')

                        // JS Global Compulsory
                        ->prependFile($this->basePath() . '/assets/vendor/bootstrap/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/popper.js/dist/umd/popper.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/jquery-migrate/dist/jquery-migrate.min.js')
                        ->prependFile($this->basePath() . '/assets/vendor/jquery/dist/jquery.min.js');
                        ?>

                        <script src="/eosjs-browser-master/eosjs-browser.js"></script>
                        <script src="/eosjs-browser-master/main.js"></script>

  </head>
  <body>
      <!-- ========== HEADER ========== -->
      <header id="header" class="u-header u-header--abs-top-md u-header--bg-transparent u-header--show-hide-md"
              data-header-fix-moment="500"
              data-header-fix-effect="slide">
        <!-- Search -->
        <div id="searchPushTop" class="u-search-push-top">
          <div class="container position-relative">
            <div class="u-search-push-top__content">
              <!-- Close Button -->
              <button type="button" class="close u-search-push-top__close-btn"
                      aria-haspopup="true"
                      aria-expanded="false"
                      aria-controls="searchPushTop"
                      data-unfold-type="jquery-slide"
                      data-unfold-target="#searchPushTop">
                <span aria-hidden="true">&times;</span>
              </button>
              <!-- End Close Button -->

              <!-- Input -->
              <form class="js-focus-state input-group input-group-lg">
                <input type="search" class="form-control" placeholder="Search Front" aria-label="Search Front">
                <div class="input-group-append">
                  <button type="button" class="btn btn-primary">Search</button>
                </div>
              </form>
              <!-- End Input -->

              <!-- Content -->
              <div class="row d-none d-md-flex mt-7">
                <div class="col-sm-6">
                  <strong class="d-block mb-2">Quick Links</strong>

                  <div class="row">
                    <!-- List Group -->
                    <div class="col-6">
                      <div class="list-group list-group-transparent list-group-flush list-group-borderless">
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Search Results List
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Search Results Grid
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          About
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Services
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Invoice
                        </a>
                      </div>
                    </div>
                    <!-- End List Group -->

                    <!-- List Group -->
                    <div class="col-6">
                      <div class="list-group list-group-transparent list-group-flush list-group-borderless">
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Profile
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          User Contacts
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Reviews
                        </a>
                        <a class="list-group-item list-group-item-action" href="#">
                          <span class="fas fa-angle-right list-group-icon"></span>
                          Settings
                        </a>
                      </div>
                    </div>
                    <!-- End List Group -->
                  </div>
                </div>

                <div class="col-sm-6">
                  <!-- Banner -->
                  <div class="rounded u-search-push-top__banner">
                    <div class="d-flex align-items-center">
                      <div class="u-search-push-top__banner-container">
                        <img class="img-fluid u-search-push-top__banner-img" src="/assets/img/mockups/img3.png" alt="Image Description">
                        <img class="img-fluid u-search-push-top__banner-img" src="/assets/img/mockups/img2.png" alt="Image Description">
                      </div>

                      <div>
                        <div class="mb-4">
                          <strong class="d-block mb-2">Featured Item</strong>
                          <p>Create astonishing web sites and pages.</p>
                        </div>
                        <a class="btn btn-xs btn-soft-success transition-3d-hover" href="<?php echo $this->url('home'); ?>">Apply Now <span class="fas fa-angle-right ml-2"></span></a>
                      </div>
                    </div>
                  </div>
                  <!-- End Banner -->
                </div>
              </div>
              <!-- End Content -->
            </div>
          </div>
        </div>
        <!-- End Search -->

        <div class="u-header__section">
          <!-- Topbar -->
          <div class="container u-header__hide-content pt-2">
            <div class="d-flex align-items-center">
              <!-- Language -->
              <div class="position-relative">
                <a id="languageDropdownInvoker" class="dropdown-nav-link dropdown-toggle d-flex align-items-center" href="javascript:;" role="button"
                   aria-controls="languageDropdown"
                   aria-haspopup="true"
                   aria-expanded="false"
                   data-unfold-event="hover"
                   data-unfold-target="#languageDropdown"
                   data-unfold-type="css-animation"
                   data-unfold-duration="300"
                   data-unfold-delay="300"
                   data-unfold-hide-on-scroll="true"
                   data-unfold-animation-in="slideInUp"
                   data-unfold-animation-out="fadeOut">
                   <img class="dropdown-item-icon" src="/assets/vendor/flag-icon-css/flags/4x3/ph.svg" alt="SVG">
                  <span class="d-inline-block d-sm-none">US</span>
                  <span class="d-none d-sm-inline-block">Philippines</span>
                </a>

                <div id="languageDropdown" class="dropdown-menu dropdown-unfold" aria-labelledby="languageDropdownInvoker">
                  <a class="dropdown-item active" href="#">English</a>
                  <a class="dropdown-item" href="#">Deutsch</a>
                  <a class="dropdown-item" href="#">Español‎</a>
                </div>
              </div>
              <!-- End Language -->

              <div class="ml-auto">
                <!-- Jump To -->
                <div class="d-inline-block d-sm-none position-relative mr-2">
                  <a id="jumpToDropdownInvoker" class="dropdown-nav-link dropdown-toggle d-flex align-items-center" href="javascript:;" role="button"
                     aria-controls="jumpToDropdown"
                     aria-haspopup="true"
                     aria-expanded="false"
                     data-unfold-event="hover"
                     data-unfold-target="#jumpToDropdown"
                     data-unfold-type="css-animation"
                     data-unfold-duration="300"
                     data-unfold-delay="300"
                     data-unfold-hide-on-scroll="true"
                     data-unfold-animation-in="slideInUp"
                     data-unfold-animation-out="fadeOut">
                    Jump to
                  </a>

                  <div id="jumpToDropdown" class="dropdown-menu dropdown-unfold" aria-labelledby="jumpToDropdownInvoker">
                    <a class="dropdown-item" href="#">Help</a>
                    <a class="dropdown-item" href="#">Contacts</a>
                  </div>
                </div>
                <!-- End Jump To -->

                <!-- Links -->
                <div class="d-none d-sm-inline-block ml-sm-auto">
                  <ul class="list-inline mb-0">
                    <li class="list-inline-item mr-0">
                      <a class="u-header__navbar-link" href="#">Help</a>
                    </li>
                    <li class="list-inline-item mr-0">
                      <a class="u-header__navbar-link" href="#">Contacts</a>
                    </li>
                  </ul>
                </div>
                <!-- End Links -->
              </div>

              <ul class="list-inline ml-2 mb-0">
                <!-- Search -->
                <li class="list-inline-item">
                  <a class="btn btn-xs btn-icon btn-text-secondary" href="javascript:;" role="button"
                          aria-haspopup="true"
                          aria-expanded="false"
                          aria-controls="searchPushTop"
                          data-unfold-type="jquery-slide"
                          data-unfold-target="#searchPushTop">
                    <span class="fas fa-search btn-icon__inner"></span>
                  </a>
                </li>
                <!-- End Search -->
              </ul>
            </div>
          </div>
          <!-- End Topbar -->

          <div id="logoAndNav" class="container">
            <!-- Nav -->
            <nav class="js-mega-menu navbar navbar-expand-md u-header__navbar u-header__navbar--no-space">
              <!-- Logo -->
              <a class="navbar-brand u-header__navbar-brand u-header__navbar-brand-center" href="<?php echo $this->url('home'); ?>" aria-label="Front">
                <img src="/img/eos_spinning_logo2.gif">
                <span class="u-header__navbar-brand-text">PEOS</span>
              </a>
              <!-- End Logo -->

              <!-- Responsive Toggle Button -->
              <button type="button" class="navbar-toggler btn u-hamburger"
                      aria-label="Toggle navigation"
                      aria-expanded="false"
                      aria-controls="navBar"
                      data-toggle="collapse"
                      data-target="#navBar">
                <span id="hamburgerTrigger" class="u-hamburger__box">
                  <span class="u-hamburger__inner"></span>
                </span>
              </button>
              <!-- End Responsive Toggle Button -->

              <!-- Navigation -->
              <div id="navBar" class="collapse navbar-collapse u-header__navbar-collapse">
                <ul class="navbar-nav u-header__navbar-nav">
                  <li class="nav-item u-header__nav-item">
                    <a class="nav-link u-header__nav-link" href="<?php echo $this->url('home'); ?>">Home</a>
                  </li>

                  <li class="nav-item u-header__nav-item">
                    <a class="nav-link u-header__nav-link" href="#">Projects</a>
                  </li>

                  <li class="nav-item u-header__nav-item">
                    <a class="nav-link u-header__nav-link" href="#">Investors</a>
                  </li>

                  <li class="nav-item u-header__nav-item">
                    <a class="nav-link u-header__nav-link" href="<?php echo $this->url('supplier'); ?>">Suppliers</a>
                  </li>

                  <li class="nav-item u-header__nav-item">
                    <a class="nav-link u-header__nav-link" href="<?php echo $this->url('incentive'); ?>">Incentives</a>
                  </li>

                  <!-- Button -->
                  <li class="nav-item u-header__nav-last-item">
                    <a class="btn btn-sm btn-primary transition-3d-hover" href="<?php echo $this->url('project', array('action' => 'create',)); ?>">
                      Start A Project
                    </a>
                  </li>
                  <!-- End Button -->
                </ul>
              </div>
              <!-- End Navigation -->
            </nav>
            <!-- End Nav -->
          </div>
        </div>
      </header>
      <!-- ========== END HEADER ========== -->

      <!-- ========== MAIN CONTENT ========== -->
      <main id="content" role="main">
        <?php echo $this->content; ?>
      </main>
      <!-- ========== END MAIN CONTENT ========== -->

      <!-- ========== FOOTER ========== -->
      <footer>
        <!-- Lists -->
        <div class="border-bottom">
          <div class="container space-2">
            <div class="row justify-content-md-between">
              <div class="col-sm-4 col-lg-2 mb-4 mb-lg-0">
                <h4 class="h6 font-weight-semi-bold">About</h4>

                <!-- List Group -->
                <ul class="list-group list-group-flush list-group-borderless mb-0">
                  <li><a class="list-group-item list-group-item-action" href="#">About</a></li>
                  <li><a class="list-group-item list-group-item-action" href="#">Services</a></li>
                  <li><a class="list-group-item list-group-item-action" href="#">Careers</a></li>
                </ul>
                <!-- End List Group -->
              </div>

              <div class="col-sm-4 col-lg-2 mb-4 mb-lg-0">
                <h4 class="h6 font-weight-semi-bold">Account</h4>

                <!-- List Group -->
                <ul class="list-group list-group-flush list-group-borderless mb-0">
                  <li><a class="list-group-item list-group-item-action" href="<?php echo $this->url('project', array('action' => 'create',)); ?>">Create Project</a></li>
                  <li><a class="list-group-item list-group-item-action" href="#">Investors</a></li>
                  <li><a class="list-group-item list-group-item-action" href="<?php echo $this->url('supplier'); ?>">Suppliers</a></li>
                  <li><a class="list-group-item list-group-item-action" href="<?php echo $this->url('incentive'); ?>">Earn Incentives</a></li>
                </ul>
                <!-- End List Group -->
              </div>

              <div class="col-sm-4 col-lg-2 mb-4 mb-lg-0">
                <h4 class="h6 font-weight-semi-bold">Resources</h4>

                <!-- List Group -->
                <ul class="list-group list-group-flush list-group-borderless mb-0">
                  <li><a class="list-group-item list-group-item-action" href="#">Help</a></li>
                  <li><a class="list-group-item list-group-item-action" href="#">Terms</a></li>
                  <li><a class="list-group-item list-group-item-action" href="#">Privacy</a></li>
                </ul>
                <!-- End List Group -->
              </div>

              <div class="col-md-6 col-lg-4">
                <h4 class="h6 font-weight-semi-bold mb-4">We are driven to deliver results for all your businesses.</h4>

                <!-- Button -->
                <button type="button" class="btn btn-xs btn-dark btn-wide transition-3d-hover text-left mb-2 mr-1">
                  <span class="media align-items-center">
                    <span class="fab fa-apple fa-2x mr-3"></span>
                    <span class="media-body">
                      <span class="d-block">Download on the</span>
                      <strong class="font-size-1">App Store</strong>
                    </span>
                  </span>
                </button>
                <!-- End Button -->

                <!-- Button -->
                <button type="button" class="btn btn-xs btn-dark btn-wide transition-3d-hover text-left mb-2">
                  <span class="media align-items-center">
                    <span class="fab fa-google-play fa-2x mr-3"></span>
                    <span class="media-body">
                      <span class="d-block">Get it on</span>
                      <strong class="font-size-1">Google Play</strong>
                    </span>
                  </span>
                </button>
                <!-- End Button -->
              </div>
            </div>
          </div>
        </div>
        <!-- End Lists -->

        <!-- Copyright -->
        <div class="container text-center space-1">
          <!-- Logo -->
          <a class="d-inline-flex align-items-center mb-2" href="<?php echo $this->url('home'); ?>" aria-label="Front">
            <img src="/img/eos_spinning_logo2.gif">
            <span class="u-header__navbar-brand-text">PEOS</span>
          </a>
          <!-- End Logo -->
          <p class="small text-muted">&copy; ProsperEOS. 2018 Team Gigamike. All rights reserved.</p>
        </div>
        <!-- End Copyright -->
      </footer>
      <!-- ========== END FOOTER ========== -->

      <!-- Go to Top -->
      <a class="js-go-to u-go-to" href="#"
        data-position='{"bottom": 15, "right": 15 }'
        data-type="fixed"
        data-offset-top="400"
        data-compensation="#header"
        data-show-effect="slideInUp"
        data-hide-effect="slideOutDown">
        <span class="fas fa-arrow-up u-go-to__inner"></span>
      </a>
      <!-- End Go to Top -->

      <!-- JS Plugins Init. -->
    <script>
      $(window).on('load', function () {
        // initialization of HSMegaMenu component
        $('.js-mega-menu').HSMegaMenu({
          event: 'hover',
          pageContainer: $('.container'),
          breakpoint: 767.98,
          hideTimeOut: 0
        });

        // initialization of svg injector module
        $.HSCore.components.HSSVGIngector.init('.js-svg-injector');
      });

      $(document).on('ready', function () {
        // initialization of header
        $.HSCore.components.HSHeader.init($('#header'));

        // initialization of unfold component
        $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
          afterOpen: function () {
            $(this).find('input[type="search"]').focus();
          }
        });

        // initialization of malihu scrollbar
        $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));

        // initialization of forms
        $.HSCore.components.HSFocusState.init();

        // initialization of form validation
        $.HSCore.components.HSValidation.init('.js-validate', {
          rules: {
            confirmPassword: {
              equalTo: '#signupPassword'
            }
          }
        });

        // initialization of show animations
        $.HSCore.components.HSShowAnimation.init('.js-animation-link');

        // initialization of fancybox
        $.HSCore.components.HSFancyBox.init('.js-fancybox');

        // initialization of text animation (typing)
        var typed = new Typed(".u-text-animation.u-text-animation--typing", {
          strings: ["more professional.", "perfect in every way.", "astonishing."],
          typeSpeed: 60,
          loop: true,
          backSpeed: 25,
          backDelay: 1500
        });

        // initialization of slick carousel
        $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');

        // initialization of go to
        $.HSCore.components.HSGoTo.init('.js-go-to');
      });
    </script>

    <?php echo $this->inlineScript() ?>

    <script>function scrollFunction(){document.body.scrollTop>20||document.documentElement.scrollTop>20?document.getElementById("cd-top").style.display="block":document.getElementById("cd-top").style.display="none"}function topFunction(){$("html, body").stop().animate({scrollTop:0},500,"swing",function(){})}window.onscroll=function(){scrollFunction()};</script>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/59eaf2b94854b82732ff6d20/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
  </body>
</html>
